/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CameraVisionRouteImport } from './routes/camera-vision'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as EChallanRouteImport } from './routes/e-challan'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SimulatorRouteImport } from './routes/simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraVisionRoute = CameraVisionRouteImport.update({
  id: '/camera-vision',
  path: '/camera-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const EChallanRoute = EChallanRouteImport.update({
  id: '/e-challan',
  path: '/e-challan',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/camera-vision': typeof CameraVisionRoute
  '/deployment': typeof DeploymentRoute
  '/dispatch': typeof DispatchRoute
  '/e-challan': typeof EChallanRoute
  '/incidents': typeof IncidentsRoute
  '/risk': typeof RiskRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/camera-vision': typeof CameraVisionRoute
  '/deployment': typeof DeploymentRoute
  '/dispatch': typeof DispatchRoute
  '/e-challan': typeof EChallanRoute
  '/incidents': typeof IncidentsRoute
  '/risk': typeof RiskRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/camera-vision': typeof CameraVisionRoute
  '/deployment': typeof DeploymentRoute
  '/dispatch': typeof DispatchRoute
  '/e-challan': typeof EChallanRoute
  '/incidents': typeof IncidentsRoute
  '/risk': typeof RiskRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/camera-vision'
    | '/deployment'
    | '/dispatch'
    | '/e-challan'
    | '/incidents'
    | '/risk'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/camera-vision'
    | '/deployment'
    | '/dispatch'
    | '/e-challan'
    | '/incidents'
    | '/risk'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/camera-vision'
    | '/deployment'
    | '/dispatch'
    | '/e-challan'
    | '/incidents'
    | '/risk'
    | '/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CameraVisionRoute: typeof CameraVisionRoute
  DeploymentRoute: typeof DeploymentRoute
  DispatchRoute: typeof DispatchRoute
  EChallanRoute: typeof EChallanRoute
  IncidentsRoute: typeof IncidentsRoute
  RiskRoute: typeof RiskRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-vision': {
      id: '/camera-vision'
      path: '/camera-vision'
      fullPath: '/camera-vision'
      preLoaderRoute: typeof CameraVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-challan': {
      id: '/e-challan'
      path: '/e-challan'
      fullPath: '/e-challan'
      preLoaderRoute: typeof EChallanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CameraVisionRoute: CameraVisionRoute,
  DeploymentRoute: DeploymentRoute,
  DispatchRoute: DispatchRoute,
  EChallanRoute: EChallanRoute,
  IncidentsRoute: IncidentsRoute,
  RiskRoute: RiskRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
